FROM node:22-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json* ./
COPY apps/api/package.json ./apps/api/package.json
COPY packages/shared/package.json ./packages/shared/package.json

RUN npm install

COPY apps/api ./apps/api
COPY packages/shared ./packages/shared
COPY infra ./infra

EXPOSE 4000

RUN chmod +x /app/infra/entrypoint-api.sh

CMD ["bash", "/app/infra/entrypoint-api.sh"]
